### ISSUE TITLE
additional (pre) steps

### ISSUE THREAD

**Issue by BenGardiner** [belvedere-yocto/belvedere_manifest#1]
Hi, the steps in the README.md refer to meta-rdk/setup-environment. The meta-rdk layer isn't in this manifest's .xml nor is it specified where to get it from in the README.

I know this layer and where to get it from; but which branch do I checkout? Also are there other layers implicitly required which are not specified here in the xml or README?

**Comment by s-maynard** [comment]
This code has been consumed into RDK and will be available on CMF.  Once it is available this repo will be going away - please don't base any projects on it...

**Comment by s-maynard** [comment]
You can try building stand-alone with these instructions:
https://github.com/belvedere-yocto/meta-rdk-belvedere/blob/master/README.md
